In [4]:
import numpy as np
from numpy import linalg

Problem 1


In [ ]:
forces = np.array([150, 200, 250, 300, 350])
x = .1
k = forces/x
print(k)

Problem 2

In [31]:
pairs = [(20, 100), (30, 150), (40,200)]
m = 2 # kilograms
specific_heat = 4.18 #J/(kg*K)
heat_process = []

def heat(mass,c,delta_T):
    return mass*c*delta_T

for pair in pairs:
    diff = pair[1] - pair[0]
    heat_process.append(heat(2,4.18,diff))

print(heat_process)


[668.8, 1003.1999999999999, 1337.6]


Problem 3

In [6]:
a = np.random.randint(9, size = (3, 4))
print(a.shape)

(3, 4)


In [4]:
a = np.random.randint(9, size=(3, 4))
print(a.mean())

4.5


In [3]:
a = np.random.randint(9, size=(3,4))
print(a.min(),a.max())

0 8


In [ ]:
#problem 4 - pandas
import pandas as pd



Problem 7a

In [25]:
a = np.array([[3, -2, 0, -1],[0, 2, 2, 1],[1,-2,-3,-2],[0, 1, 2, 1]])
inverse = np.linalg.inv(a)
print(inverse)

[[  1.   1.  -2.  -4.]
 [  0.   1.   0.  -1.]
 [ -1.  -1.   3.   6.]
 [  2.   1.  -6. -10.]]


Problem 7b

In [26]:
a = np.array([[3, -2, 0, -1],[0, 2, 2, 1],[1,-2,-3,-2],[0, 1, 2, 1]])
print(np.linalg.matrix_rank(a))

4


Problem 7c

In [6]:
a = np.array([[3, -2, 0, -1],[0, 2, 2, 1],[1,-2,-3,-2],[0, 1, 2, 1]])
det_a = np.linalg.det(a)

if det_a == 0:
    print(f"Matrix is singular. It cannot be inverted.")
else:
    print(f"Matrix is non-singular. We can invert it.")

Matrix is non-singular. We can invert it.


Problem 7d

In [4]:
c = np.array([[3, -2, 0, -1],[0, 2, 2, 1],[1,-2,-3,-2],[0, 1, 2, 1]]) 
print(np.linalg.cond(c))


88.09012296703409


The above matrix is ill conditioned, we cannot trust the results of the solver function.



Problem 8a

In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
x = np.linalg.solve(a,b)
print(x)

[-4.   4.5]


Problem 8b

In [8]:
a = np.array([[2, 3, -4],[1, -2, 1],[3, -1, 2]])
b = np.array([5, -1, 10])
x = np.linalg.solve(a, b)
print(x)

[2.73913043 3.08695652 2.43478261]
