In [1]:
import numpy as np
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
arr_range = np.arange(10,30,5)
print(arr_range)

[10 15 20 25]


In [7]:
arr_lin = np.linspace(0, 2, 9)
print(arr_lin)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [9]:
arr_rand = np.random.random((2, 2))
print(arr_rand)

[[0.60424643 0.46970858]
 [0.84262724 0.07171913]]


In [10]:
arr_rand_int = np.random.randint(7, size=(3, 3))
print(arr_rand_int)

[[4 6 5]
 [0 6 4]
 [3 6 6]]


In [11]:
arr_exp_con = np.exp([2+1j,2-1j])
print(arr_exp_con)

[3.99232405+6.21767631j 3.99232405-6.21767631j]


In [12]:
arr_empty = np.empty((2,2))
print(arr_empty)

[[0.60424643 0.46970858]
 [0.84262724 0.07171913]]


In [14]:
arr_full = np.full((2,2), 7)
print(arr_full)

[[7 7]
 [7 7]]


In [15]:
a_2d = np.array(([[1,2,3,4],
                  [5,6,7,8],
                  [8,10,11,12]]))
print(a_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8 10 11 12]]


In [17]:
a_2d = np.arange(1,13,1).reshape(3,4)
print(a_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(a_2d[2][1])

10


In [19]:
print(a_2d[:,1])

[ 2  6 10]


In [20]:
a_2d[2, 1] = 16
print(a_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 16 11 12]]


In [21]:
a_2d[:,1] = [4, 12, 20]
print(a_2d)

[[ 1  4  3  4]
 [ 5 12  7  8]
 [ 9 20 11 12]]


In [26]:
print(a_2d[:,::2])


[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [27]:
mat = np.ones((5,5),dtype = int)
mat[1:4,1:4] = np.zeros((3,3))
mat[2, 2] = 9
print(mat)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [28]:
from numpy import linalg

In [29]:
narray = np.arange(1,5)
normal = np.linalg.norm(narray, ord=2)
print(normal)

5.477225575051661


In [50]:
a = np.array([[4, 3, -5,], [-2, -4, 5], [7, 8, 0], [1, 0, 2],[9, 1, -6]])
b = np.array([2, 5, -3, 1, 6])

x = np.linalg.solve(a, b)
print(x)

LinAlgError: Last 2 dimensions of the array must be square

In [48]:
#error LinAlgError: Singular matrix

#error LinAlgError: Last 2 dimensions of the array must be square

In [47]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
#full rank and well conditioned matrix

a = np.array([[1, 2, 3],[8, 6,2 ],[5, 1, 3]])
det_a = linalg.det(a)
print(det_a)
inv_a = linalg.inv(a)
print(inv_a)
rank_a = linalg.matrix_rank(a)
print(rank_a)
shape_a = a.shape
print(shape_a)

-78.0
[[-0.20512821  0.03846154  0.17948718]
 [ 0.17948718  0.15384615 -0.28205128]
 [ 0.28205128 -0.11538462  0.12820513]]
3
(3, 3)
