Problem 1

matrix of coefficients
let Ca be x Cc be y and Cd be w

Ca0 is given, Cc0 is zero, so is Cd

solve for x, y, z, using a solver, these are the concentrations

In [1]:
import numpy as np
    


def three_by_three_method(Ca0, Cc0, Cd0, k1, k2, tau):
    a2 = np.array([[1 + k1 * tau, 0, 0],
                  [-1 * k1 * tau, k2 * tau + 1, 0],
                  [0, -1 * k2 * tau, 1]])
    b2 = [Ca0, Cc0, Cd0]
    return np.linalg.solve(a2, b2)


sol = three_by_three_method(2.2, 0, 0, 2.3 / 60, 4.5 / 60, 2.5 * 60)
print(f'Ca equals {sol[0]} mol / L')
print(f'Cc equals {sol[1]} mol / L')
print(f'Cd equals {sol[2]} mol / L')


Ca equals 0.32592592592592595 mol / L
Cc equals 0.15298563869992443 mol / L
Cd equals 1.7210884353741496 mol / L


In [78]:
import numpy as np

species_mol_frac = np.array([[7, 18, 15, 24],[3, 25, 10, 65], [55, 41, 55, 9], [35, 16, 20, 2]])

# concatenate the mol frac. vectors into a matrix

# initial flow rate vector a.k.a b vector
fa0 = 80
b = np.array([15, 25, 40, 20]) * fa0
# reminder to self: doing this as a list adds 80 more elements, oops!

if np.linalg.det(species_mol_frac) == 0:
    print("Matrix is singular")
else:
    print("Matrix is not singular")

if np.linalg.cond(species_mol_frac) >= 1000:
    print("Matrix is ill-conditioned")
else:
    print("Matrix is well conditioned")

def degrees_freedom(n, m):
    if n == m:
        print("You will have a unique solution")
    elif n < m:
        print("Too many unknowns, solution will not converge. ")
    else:
        print("You have infinite solutions")
      
num_eqs = len(b)
num_unknowns = len(species_mol_frac)

degrees_freedom(num_eqs, num_unknowns)
    
z = np.linalg.solve(species_mol_frac, b)

d2 = z[0]
b2 = z[1]
d3 = z[2]
b3 = z[3]

print(f'D2 is {d2} kg-mol / min')
print(f'B2 is {b2} kg-mol / min')
print(f'D3 is {d3} kg-mol / min')
print(f'B4 is {b3} kg-mol / min')
print(f'D1 is {d2 + b2} kg-mol / min')
print(f'B1 is {d3 + b3} kg-mol / min')
print(f'F total is {np.sum(z)}kg-mol / min ')

answer = np.transpose(species_mol_frac)
print(f'The composition of D1 is  {(d2/100)*answer[0]+(b2/100)*answer[1]}')
print(f'The composition of B1 is  {(d3/100)*answer[2]+(b3/100)*answer[3]}')
print(np.sum((d2/100)*answer[2]+(b2/100)*answer[3]))
print(np.sum((d3/100)*answer[2]+(b3/100)*answer[3]))

Matrix is not singular
Matrix is well conditioned
You will have a unique solution
D2 is 29.834254143646408 kg-mol / min
B2 is 14.917127071823225 kg-mol / min
D3 is 13.701657458563517 kg-mol / min
B4 is 21.546961325966844 kg-mol / min
D1 is 44.751381215469635 kg-mol / min
B1 is 35.248618784530365 kg-mol / min
F total is 80.0kg-mol / min 
The composition of D1 is  [ 4.77348066  4.62430939 22.52486188 12.82872928]
The composition of B1 is  [ 7.22651934 15.37569061  9.47513812  3.17127072]
44.751381215469635
35.248618784530365


In [27]:
import numpy as np
from numpy import linalg


def sol_vector(A, b):
    n = len(b)
    # create solution vector x
    x = np.zeros(n, float)
    for k in range(0, n - 1):  # loop for pivot eq.
        if A[k, k] == 0:  # check if the diagonal element is 0
            for j in range(n):  # if so then for all the columns
                A[k, j], A[k + 1, j] = A[k + 1, j], A[k, j]  # swap the elements for the row below
            b[k], b[k + 1] = b[k + 1], b[k]  # swap vector b but outside the column loop
        for i in range(k + 1, n):  # loop for equations below pivot eq
            lam = A[i, k] / A[k, k]
            b[i] = b[i] - lam * b[k]
            # print("b vector",b[i])
            for j in range(k, n):
                A[i, j] = A[i, j] - lam * A[k, j]
            # print("A matrix",A[i,j])

    # Stage 2 back substitution
    x[n - 1] = b[n - 1] / A[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        # print(i)
        terms = 0
        for j in range(i + 1, n):
            terms += A[i, j] * x[j]
        x[i] = (b[i] - terms) / A[i, i]
    return x


a1 = np.array([[0, 2, 1],
               [1, 1, 2],
               [2, 1, 1]], dtype=float)
b1 = np.array([4, 6, 7])
print(sol_vector(a1, b1))
print(np.linalg.solve(a1, b1))
print(f'The answers match')

[2.2 1.4 1.2]
[2.2 1.4 1.2]
The answers match


In [29]:
import numpy as np
from numpy import linalg


def sol_vector(A, b):
    n = len(b)
    # create solution vector x
    x = np.zeros(n, float)
    for k in range(0, n - 1):  # loop for pivot eq.
        if A[k, k] == 0:  # check if the diagonal element is 0
            for j in range(n):  # if so then for all the columns
                A[k, j], A[k + 1, j] = A[k + 1, j], A[k, j]  # swap the elements for the row below
            b[k], b[k + 1] = b[k + 1], b[k]  # swap vector b but outside the column loop
        for i in range(k + 1, n):  # loop for equations below pivot eq
            lam = A[i, k] / A[k, k]
            b[i] = b[i] - lam * b[k]
            # print("b vector",b[i])
            for j in range(k, n):
                A[i, j] = A[i, j] - lam * A[k, j]
            # print("A matrix",A[i,j])

    # Stage 2 back substitution
    x[n - 1] = b[n - 1] / A[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        # print(i)
        terms = 0
        for j in range(i + 1, n):
            terms += A[i, j] * x[j]
        x[i] = (b[i] - terms) / A[i, i]
    return x


C = np.array([[0, 8, -2, 5, 6],
              [1, 3, 0, 1, 7],
              [6, 0, 0, 2, -1],
              [2, 1, 2, 0, 2],
              [8, 4, 1, -2, 1]], float)

D = np.array([5, 20, 2, 3, 4], float)

print(sol_vector(C, D))


[ 1.24677899 -2.26726131 -2.38586059 -0.85398084  3.77271226]


In [97]:
a = np.array([[80, 20,0, 0],
              [70, 0, 30, 0],
              [5, 85, 10, 0],
              [100, 0, 0, 0]])
b = np.array([100, 100, 100, 100])

def degrees_freedom(n, m):
    if n == m:
        print("You will have a unique solution")
    elif n < m:
        print("Too many unknowns, solution will not converge. ")
    else:
        print("You have infinite solutions")
      
if np.linalg.det(a) == 0:
    print('Error singular matrix')
else:
    print("Proceed with matrix calculation")
    

degrees_freedom(3, 4)

if np.linalg.cond(species_mol_frac) >= 100:
    print("Matrix is ill-conditioned")
else:
    print("Matrix is well conditioned")

Error singular matrix
Too many unknowns, solution will not converge. 
Matrix is ill-conditioned
